export enum ValidationIssueType {
  MISSING_REQUIRED_FIELD = 'MISSING_REQUIRED_FIELD',
  INVALID_HS_CODE_FORMAT = 'INVALID_HS_CODE_FORMAT',
  MISSING_COUNTRY_OF_ORIGIN = 'MISSING_COUNTRY_OF_ORIGIN',
  INVALID_COUNTRY_CODE = 'INVALID_COUNTRY_CODE',
  WEIGHT_MISMATCH = 'WEIGHT_MISMATCH',
  MISSING_BILL_OF_LADING = 'MISSING_BILL_OF_LADING',
  INVALID_CONTAINER_NUMBER = 'INVALID_CONTAINER_NUMBER',
  MISSING_INVOICE_VALUE = 'MISSING_INVOICE_VALUE',
  SUSPICIOUS_INVOICE_VALUE = 'SUSPICIOUS_INVOICE_VALUE',
  WOOD_PACKAGING_UNCERTIFIED = 'WOOD_PACKAGING_UNCERTIFIED',
  STALE_ARRIVAL_DATE = 'STALE_ARRIVAL_DATE',
  DUPLICATE_SHIPMENT_REFERENCE = 'DUPLICATE_SHIPMENT_REFERENCE'
}

export enum ValidationRuleName {
  MISSING_FIELDS_RULE = 'MissingFieldsRule',
  INVALID_HS_CODE_RULE = 'InvalidHSCodeRule',
  MISSING_COUNTRY_RULE = 'MissingCountryRule',
  WEIGHT_MISMATCH_RULE = 'WeightMismatchRule',
  MISSING_BILL_OF_LADING_RULE = 'MissingBillOfLadingRule',
  INVALID_CONTAINER_RULE = 'InvalidContainerRule',
  SUSPICIOUS_INVOICE_RULE = 'SuspiciousInvoiceRule',
  WOOD_PACKAGING_RULE = 'WoodPackagingRule',
  ARRIVAL_DATE_RULE = 'ArrivalDateRule',
  DUPLICATE_SHIPMENT_RULE = 'DuplicateShipmentRule'
}

export const VALIDATION_THRESHOLDS = {
  SUSPICIOUS_INVOICE_MAX: 10000000,
  STALE_ARRIVAL_DAYS_LIMIT: 30,
};

export const TIME_CONSTANTS = {
  MS_IN_A_DAY: 1000 * 60 * 60 * 24,
};

export const PACKAGING_KEYWORDS = {
  WOOD_INDICATORS: ['wood', 'pallet', 'crate'],
};

export const REQUIRED_SHIPMENT_FIELDS = [
  'exporter', 
  'importer', 
  'commercialInvoiceNumber', 
  'goodsDescription'
];
